# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  tags:
   include: [ 'prod' ]

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: CmdLine@2
      inputs:
        script: cp $(Build.SourcesDirectory)/src/BlogCore.Authority/Dockerfile $(Build.SourcesDirectory)/
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: latest
    - task: SSH@0
      inputs:
        sshEndpoint: 'myssh'
        runOptions: 'inline'
        inline: |
          sudo docker kill ssoapi
          sudo docker rm ssoapi
          sudo docker rmi witeem/blogcoreauthority
          sudo docker pull witeem/blogcoreauthority
          sudo docker run -it --name ssoapi -p 9000:80 -d witeem/blogcoreauthority
        failOnStdErr: false
        interactiveSession: true
        readyTimeout: '20000'
    
