# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  tags:
    include: [ prod-* ]

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  appsettings: appsettings.Production.json

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - bash: |
        echo "ready to execute command"
        cd src/BlogCore/
        ls
        sed -i 's/{ConnectionString}/$(ConnectionString)/g' $(appsettings)
        sed -i 's/{ConnKey}/$(ConnKey)/g' $(appsettings)
        sed -i 's/{ConnIV}/$(ConnIV)/g' $(appsettings)
        echo "================= print file $(appsettings) start ===================="
        cat $(appsettings) | while read line; do echo $line; done
        echo "================= print file $(appsettings) end ===================="
        echo "command executed"

    - task: CmdLine@2
      inputs:
        script: |
          cp $(Build.SourcesDirectory)/src/BlogCore/Dockerfile $(Build.SourcesDirectory)/

    - task: Docker@2
      inputs:
        containerRegistry: 'mydocker'
        repository: 'witeem/blogcore'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: latest
    - task: SSH@0
      inputs:
        sshEndpoint: 'myssh'
        runOptions: 'inline'
        inline: |
          sudo docker kill blogapi
          sudo docker rm blogapi
          sudo docker rmi witeem/blogcore
          sudo docker pull witeem/blogcore
          sudo docker run -it --name blogapi -p 9001:80 -d witeem/blogcore
        failOnStdErr: false
        interactiveSession: true
        readyTimeout: '20000'
    
