# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: CmdLine@2
      inputs:
        script: cp $(Build.SourcesDirectory)/src/BlogCore/Dockerfile $(Build.SourcesDirectory)/
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: latest
    - task: SSH@0
      inputs:
        sshEndpoint: 'myssh'
        runOptions: 'inline'
        inline: |
          sudo docker kill blogapi
          sudo docker rm blogapi
          sudo docker rmi witeem/blogcore
          sudo docker pull witeem/blogcore
          sudo docker run -it --name blogapi -p 9001:80 -d witeem/blogcore
        failOnStdErr: false
        interactiveSession: true
        readyTimeout: '20000'
    
