# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  tags:
    include: [ prod-* ]

resources:
- repo: self

parameters:
  - name: appsettings
    type: string
    values:
      - src/BlogCore/appsettings.Production.json
  
variables:
- group: witeem-blog
- name: Connection
  value: $[variables.ConnectionString]
- name: Key
  value: $[variables.ConnKey]
- name: IV
  value: $[variables.ConnIV]

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: CmdLine@2
      inputs:
        script: |
          cp $(Build.SourcesDirectory)/src/BlogCore/Dockerfile $(Build.SourcesDirectory)/
          ls ${{parameters.appsettings}} -l
          chmod 666 ${{parameters.appsettings}}
          sed  -i  's/{ConnectionString}/$(Connection)/g'  ${{parameters.appsettings}}
          sed  -i  's/{ConnKey}/$(Key)/g'  ${{parameters.appsettings}}
          sed  -i  's/{ConnIV}/$(IV)/g'  ${{parameters.appsettings}}
          echo "================= print file ${{parameters.appsettings}} start ===================="
          cat ${{parameters.appsettings}} | while read line; do echo $line; done
          echo "================= print file ${{parameters.appsettings}} end ===================="
          echo "command executed"
    - task: Docker@2
      inputs:
        containerRegistry: 'mydocker'
        repository: 'witeem/blogcore'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: latest
    - task: SSH@0
      inputs:
        sshEndpoint: 'myssh'
        runOptions: 'inline'
        inline: |
          sudo docker kill blogapi
          sudo docker rm blogapi
          sudo docker rmi witeem/blogcore
          sudo docker pull witeem/blogcore
          sudo docker run -it --name blogapi -p 9001:80 -d witeem/blogcore
        failOnStdErr: false
        interactiveSession: true
        readyTimeout: '20000'
    
